import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='bg-[#DDEAFF]' style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          border: '1px solid black',
          height: '5vh',
          fontWeight: 'bold',
          maxWidth: '100%'

          
        }}>
          <nav style={{
            
          }}>
            <a style={{
              marginInline: '2vw'
            }}>Home</a>
            <a style={{
              marginInline: '2vw'
            }}>About</a>
            <a style={{
              marginInline: '2vw'
            }}>Contact</a>
            <a style={{
              marginInline: '2vw'
            }}>Contact</a>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
